### ISSUE TITLE
how to generate the media files

### ISSUE THREAD

**Issue by ForgetMe17** [InRaysee/vr-dash-tile-player#1]
hi @InRaysee 
i have downloaded dataset and it worked fine locally, great work!
i want to know how to creat the media files on my own, for example, if i have a panoramic video, how can i get the dash tile streams.

**Comment by InRaysee** [comment]
> hi @InRaysee
> i have downloaded dataset and it worked fine locally, great work!
> i want to know how to creat the media files on my own, for example, if i have a panoramic video, how can i get the dash tile streams.

Hi! Thanks for your question.

Sorry for my poor expressions before. I have updated the [README.md](https://github.com/InRaysee/vr-dash-tile-player/blob/master/README.md) file with specific steps of media preprocessing. Please check.

BTW we're new in this area. Just feel free to start a communication with us if any questions. XD

**Comment by ForgetMe17** [comment]
Thanks for your quick reply! @InRaysee 
I am also new in this area, i have tested many other frameworks on vr-tile-player, this aframe-based player is the best for me.
I am planning on getting through your work and apply this to my research like network traffice analysis on vr streaming service.
Thanks again for sharing your project! Hope we can communicate on any issue here :)
