### ISSUE TITLE
Cannot download the Precessed dataset CMPVP907 

### ISSUE THREAD

**Issue by Gabrielgca** [InRaysee/vr-dash-tile-player#10]
Hello,

I just started to use your player and wanted to use it with the same dataset that you used: CMPVP907. However, I am not able to download the file.

I am using the google translate to guide me in the website, so I'm also pretty sure that I'm missing something.

Clicking in the link in the button in the  middle I have the following message:

<img src="https://user-images.githubusercontent.com/65353733/184943841-4b3addfa-e367-47d3-a7fa-6f1c24246aea.png" width="600">

Which translating the message in red: _External links do not support cloud decompression_

In the second attempt I clicked in the following button:

<img src="https://user-images.githubusercontent.com/65353733/184944419-cbc4a3c6-14ee-4ab4-98e9-79a3b0745294.png" width="600">

After it loaded I have the following message:
<img src="https://user-images.githubusercontent.com/65353733/184945788-f3fc5211-7e0a-4988-829a-ae19d416f120.png" width="600">
Translating the highlighted message: _The new version of the client has been installed, but it still cannot be downloaded, check the reason_

When I click in the blue button it starts to download the BaiduNetdisk_7.19.0.18, which I didn't install because, having zero skills in chinese, I have no idea of what is downloading.

Can you guys help me? I'm really looking forward to test your player because it would be of great value for my research!

**Comment by InRaysee** [comment]
Hi! Sorry for your inconvenience. I just uploaded a new version of our dataset which is easier for you to reach. Please let me know if still any problem.

( Preprocessed dataset CQ07 in Google Cloud Drive: https://drive.google.com/file/d/1yQpNv4Mpe1OQzgXb6epJdvo44YGX3jDH/view?usp=sharing )

**Comment by Gabrielgca** [comment]
Hello @InRaysee ,

Thanks for your quick reply. Now I was able to download the dataset. I will be working with it in next days!
