### ISSUE TITLE
Research usage

### ISSUE THREAD

**Issue by ForgetMe17** [InRaysee/vr-dash-tile-player#4]
Hi @InRaysee 
I am currently working on analysing the throughput of the tile streaming and planning on an experiment based on this player.
What research field are you currently working on? And have you done any experiments based on this player?

**Comment by InRaysee** [comment]
Hi @ForgetMe17 
We're working on some new ABR methods based on this platform, including transmission with MEC units.

**Comment by ForgetMe17** [comment]
> Hi @ForgetMe17
> We're working on some new ABR methods based on this platform, including transmission with MEC units.

Have you published any paper? Maybe I can go through your work to get better understanding of this player.

**Comment by InRaysee** [comment]
> > Hi @ForgetMe17
> > We're working on some new ABR methods based on this platform, including transmission with MEC units.
> 
> Have you published any paper? Maybe I can go through your work to get better understanding of this player.

Not yet. We're still working on it XD. Just feel free to contact me if you want.

**Comment by ForgetMe17** [comment]
Hi @InRaysee,
have you used any vr headset like htc vive or oculus to work this player? It seems that aframe.js supports using vr headsets.

**Comment by InRaysee** [comment]
> Hi @InRaysee,
> have you used any vr headset like htc vive or oculus to work this player? It seems that aframe.js supports using vr headsets.

Sure we're using HTC VIVE PRO EYE. However, there're some compatibility problems when connecting PC and headsets with different web browers. We're now using chromium and it seems fine.
