### ISSUE TITLE
How to fer HMD pose data?

### ISSUE THREAD

**Issue by LouHan-0325** [InRaysee/vr-dash-tile-player#5]
Hi! @InRaysee 
I want to get HMD pose data when I watch 360° videos based on this player. What API should I use?

**Comment by InRaysee** [comment]
Hi @LouHan-0325 
I think it's feasible to get HMD pose data from HMD itself instead of the player. Maybe you can try finding the APIs in the HMD's official document?

**Comment by LouHan-0325** [comment]
Thanks for your reply and advice!
