### ISSUE TITLE
Question about tile.json

### ISSUE THREAD

**Issue by Vesper0704** [InRaysee/vr-dash-tile-player#6]
Thanks for your contribution and sharing!
As we have noticed and learned, the player supports the 6-player (as a cube) displaying at the same time and we have sucessfully watched the demo in HMD through firefox. However, when we are trying to display the tiled video( 6x9 because each side is further divided into 9 tiles) json file, the player fails to work normally.
(actually there are 2 json files in the dataset and the tiled one cannot be played)
Could you please tell me the solution? Thanks a lot!

**Comment by InRaysee** [comment]
Thanks for your contact. Was there any error report in the console of your Firefox? If yes, more details on this would help us a lot to figure out the problem.

**Comment by Vesper0704** [comment]
Thanks for your reply!
Now we are able to play the video through chrome, but there are some more questions:
1. The console suggests lots of error although the player seems to work normally, such as:
Uncaught TypeError: Cannot read properties of undefined (reading 'data')
    at m.$scope.plotPoint (main.js:311)
    at updateFigures (main.js:781) 
and,
Uncaught TypeError: Cannot read properties of null (reading 'getContext') at main.js:581
2.  I am using chrome and htc vive eye pro, should I add some plugins to support watching from HMD？
3. The dataset provides the tiled json nad untiled json. I am wondering how you process the origin video into the tiled ones? cause I notice there are 54 mpds in total. We have tried to use ffmpeg to divide the video into tiles. Did you use the same way or other tools like kvazaar?
4. When I use the player to watch the tiled video, there are clear black blocks among the different pics, but the single tile is 480x480 and the whole video is 1440x1440, it should be exactly 1/3 of the picture, why are there missing parts so that they cannot make up the  complete one？
![dbab3b42f647fa8fc0a164027aacfc9](https://user-images.githubusercontent.com/64687700/135195834-ef499509-1a8d-4891-a88f-1e6cc9186136.png)


I know this can be a little bothering, but I appreciate your great patience and am looking forward to your reply.
Thanks！

**Comment by InRaysee** [comment]
Hi!

1. The functions plotPoint and updateFigures are used to print the figure in the web page (below the video player), which can show how well your video flows go with some parameters like throughput, buffer length, etc. It may be something wrong when fetching the data, but it will not affect the player.
2. At the first time I used Chrome too. But it is weird that the VR mode could not work on Chrome although some warnings showed up on Chrome saying that I was connecting to an external VR device successfully. So I found a Chromium-based browser on Steam which can play the VR videos encoded with VP9, but it was still not working well sometimes. However, we are still trying to figure out an effective way. 
3. For now FFMPEG is better for tiling, I think. But it might work slowly when trying to make a live stream.
4. Please check the file 6_3_3.html, then fix the width and height of each tile to make it suitable for the element it maps on. Or you can change the parameters in 6_3_3.html to make it suitable for your tiles.

Anyway we are also new to this area. Don't hasitate to contact us if necessary! ^^

**Comment by Vesper0704** [comment]
Thanks!
We are using Firefox browser to display the video. It supports webXR well and has greater compatibility. You can check this one for configuration: [https://www.cnblogs.com/crz2014/p/6876590.html]

**Comment by InRaysee** [comment]
Thanks!
