### ISSUE TITLE
Access this site over HTTPS to enter VR mode and grant access to the device sensors.

### ISSUE THREAD

**Issue by whp22** [InRaysee/vr-dash-tile-player#8]
When I tried SVOD to play video. The player shows
>  Access this site over HTTPS to enter VR mode and grant access to the device sensors.
![Screenshot 2022-04-11 182051](https://user-images.githubusercontent.com/79181675/163081304-9ba15e10-1525-4cd0-99ea-8367d501158b.png)
Could you please tell me how to address it?
Thanks

**Comment by InRaysee** [comment]
Hi! Thanks for your attention to this project!
This is because you're using the HTTP protocol to run this website which is not safe enough to activate the VR mode when connected with a VR device. Clicking "cancel" directly would lead you to a 2D player which is able to play 360 videos as well, but just on the normal PC monitors.
However, you can modify the configuration file of your HTTP server (e.g., if Nginx is used then modify nginx.conf) to activate transmission over HTTPS.
More details on Nginx's official websites: https://nginx.org/en/docs/http/configuring_https_servers.html
If you're using Apache or others, there should be a way to activate HTTPS as well.

**Comment by whp22** [comment]
> Hi! Thanks for your attention to this project! This is because you're using the HTTP protocol to run this website which is not safe enough to activate the VR mode when connected with a VR device. Clicking "cancel" directly would lead you to a 2D player which is able to play 360 videos as well, but just on the normal PC monitors. However, you can modify the configuration file of your HTTP server (e.g., if Nginx is used then modify nginx.conf) to activate transmission over HTTPS. More details on Nginx's official websites: https://nginx.org/en/docs/http/configuring_https_servers.html If you're using Apache or others, there should be a way to activate HTTPS as well.

Thanks for your response.  After clicking "cancel" with HTTP, the 2D player cannot play 360 video.  I will try HTTPS using Nginx, and update the result later.

**Comment by whp22** [comment]
> 
I just tried HTTPS with Nginx, but the player cannot play video even at the LVOD. I can click "play" or "pause", but nothing is shown up. ![Screenshot 2022-04-13 154642](https://user-images.githubusercontent.com/79181675/163258369-ed93bdde-c459-4971-80fe-b4d221400ef9.png)
There are lots of errors, but I think the one below is the main problem:
![Screenshot 2022-04-13 154501](https://user-images.githubusercontent.com/79181675/163258138-318c1bc5-afb1-4cef-ae04-b64a6ee2f698.png)
Sorry for my questions, I am a complete newbie at this.

**Comment by InRaysee** [comment]
Hi!
Firstly, please double check your CORS settings on your Nginx server both over HTTP and HTTPS (https://enable-cors.org/server_nginx.html), then reload Nginx successfully and try streaming again.
When you fix the CORS problem above, you can check the console again if any mistake still appears then give me a screenshot of it.

**Comment by whp22** [comment]
Thanks, I will try it again, and update the results.

**Comment by whp22** [comment]
> Hi! Firstly, please double check your CORS settings on your Nginx server both over HTTP and HTTPS (https://enable-cors.org/server_nginx.html), then reload Nginx successfully and try streaming again. When you fix the CORS problem above, you can check the console again if any mistake still appears then give me a screenshot of it.

First, thanks for your help @InRaysee. I have successfully streamed video from server to Oculus quest 2 with HTTP or HTTPS. But the built-in browser of quest2 only works with HTTPS. I also tried the firefox in quest2, which works well with both HTTPS and HTTP. BTW: there are some display bugs.

**Comment by InRaysee** [comment]
> > Hi! Firstly, please double check your CORS settings on your Nginx server both over HTTP and HTTPS (https://enable-cors.org/server_nginx.html), then reload Nginx successfully and try streaming again. When you fix the CORS problem above, you can check the console again if any mistake still appears then give me a screenshot of it.
> 
> First, thanks for your help @InRaysee. I have successfully streamed video from server to Oculus quest 2 with HTTP or HTTPS. But the built-in browser of quest2 only works with HTTPS. I also tried the firefox in quest2, which works well with both HTTPS and HTTP. BTW: there are some display bugs.

Glad to hear your good news. Sorry about the bugs in the displays since we just focused on the performance on streaming, anyway we're planning to make optimization on that when available. Don't hesitate to contact us whenever you find anything that can be modified better. Thanks.
