### ISSUE TITLE
The rotation and rotation of player

### ISSUE THREAD

**Issue by whp22** [InRaysee/vr-dash-tile-player#9]
Sorry, I really don't understand the location and rotation, how are they put together?
    "tiles": [
		[[{"src": "face0/output/stream.mpd", "width": "1440", "height": "1440", "x": 720, "y": 0, "z": 0, "rx": 0, "ry": 270, "rz": 0}]],
		[[{"src": "face1/output/stream.mpd", "width": "1440", "height": "1440", "x": -720, "y": 0, "z": 0, "rx": 0, "ry": 90, "rz": 0}]],
		[[{"src": "face2/output/stream.mpd", "width": "1440", "height": "1440", "x": 0, "y": 720, "z": 0, "rx": 90, "ry": 0, "rz": 180}]],
		[[{"src": "face3/output/stream.mpd", "width": "1440", "height": "1440", "x": 0, "y": -720, "z": 0, "rx": -90, "ry": 0, "rz": 180}]],
		[[{"src": "face4/output/stream.mpd", "width": "1440", "height": "1440", "x": 0, "y": 0, "z": -720, "rx": 0, "ry": 0, "rz": 0}]],
		[[{"src": "face5/output/stream.mpd", "width": "1440", "height": "1440", "x": 0, "y": 0, "z": 720, "rx": 0, "ry": 180, "rz": 0}]]
	],

Thanks

**Comment by InRaysee** [comment]
Hi! Glad to receive your issue.
When a dash player is initialized, it would be set up according to the default settings in settings.js which can be found in src. The modifications including info section in my code are to adopt some customized settings instead of the default ones. The usage of the function updatesettings() can be found in the API documents of dash.js. However, there are some modifications in my copied version of dash.js. For example, the original settings.js doesn’t have “info”, so you can find the modifications I did in changelog.txt. Importantly, once the src files are changed, you need to recompile it according to the instructions from dash.js.

**Comment by whp22** [comment]
Thanks a lot for this. And what are the x, y, z, rx, ry, rz? I know they are locations and rotations, but I don't know how they work, what is the coordinate system?

**Comment by whp22** [comment]
> Hi! Glad to receive your issue. When a dash player is initialized, it would be set up according to the default settings in settings.js which can be found in src. The modifications including info section in my code are to adopt some customized settings instead of the default ones. The usage of the function updatesettings() can be found in the API documents of dash.js. However, there are some modifications in my copied version of dash.js. For example, the original settings.js doesn’t have “info”, so you can find the modifications I did in changelog.txt. Importantly, once the src files are changed, you need to recompile it according to the instructions from dash.js.
> […](#)
> 在 2022年6月18日，05:17，Haopeng Wang ***@***.***> 写道： ﻿ Hi, I am a newbie at the js, I can find the 'info' in your dash.js instead of the official dash.js, so the dash.js is modified? How does this work? Thanks — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

Thanks a lot for this. And what are the x, y, z, rx, ry, rz? I know they are locations and rotations, but I don't know how they work, what is the coordinate system? Thanks

**Comment by InRaysee** [comment]
Since I put 6 flat DASH players together as a cube to build up a 360-degree space by using aframe framework, each player should have its spatial location and rotation to combine with each other perfectly. Precisely, you can check the codes in 6_1_1.html where you can find 6 faces with different locations and rotations. However, we have not used the location and rotation info in the .mpd file you mentioned as well as this info in settings.js in the current version, but we still keep them available in case of being used in the future.

**Comment by whp22** [comment]
> Since I put 6 flat DASH players together as a cube to build up a 360-degree space by using aframe framework, each player should have its spatial location and rotation to combine with each other perfectly. Precisely, you can check the codes in 6_1_1.html where you can find 6 faces with different locations and rotations. However, we have not used the location and rotation info in the .mpd file you mentioned as well as this info in settings.js in the current version, but we still keep them available in case of being used in the future.

Thanks for your answer. And I want to save the variables, like totalqoe, time, bitrate, buffer, to a file, (or set them new variables from a file). Could you give me some hints about reading and writing files? Thanks a lot.

**Comment by InRaysee** [comment]
As far as we know, web pages are not allowed to read or write local files in general for safety reasons. However, you can read the data which are saved on HTTP servers by HTTP requests. Here is an example in my codes to read a JSON file:
```
    //// Loading sources
    // Get contents through HTTP requests
    function getContents(url, callback) {
        var xhr = new XMLHttpRequest();
        xhr.open("GET", url, true);
        xhr.onload = callback;
        xhr.send();
    }

    // Read json file if json is available
     $scope.openJSON = function(url) {
        $scope.players = [];
        $scope.buffer_empty_flag = [];
        $scope.playerCount = 0;
        $scope.lon = 90;
        $scope.lat = 0;
        $scope.contents = {};
        getContents(url, function() {
            $scope.contents = JSON.parse(this.responseText);
            if ($scope.contents.ssresults && $scope.contents.ssresults != "") {
                getContents($scope.contents.baseUrl + $scope.contents.ssresults, function() {
                    $scope.ssresults = JSON.parse(this.responseText);
                });
            }
            document.getElementById('Link').style = "display: none;";
            document.getElementById('Render').style = "display: inline;";
        });
    };
```
Besides, your server needs to meet the requirement if you want to upload some data on it. One of the ways I used before is setting up a simple HTTP server that can deal with GET, POST, PUT methods. More details can be checked in some blogs on google, e.g. https://blog.anvileight.com/posts/simple-python-http-server.

**Comment by whp22** [comment]
> As far as we know, web pages are not allowed to read or write local files in general for safety reasons. However, you can read the data which are saved on HTTP servers by HTTP requests. Here is an example in my codes to read a JSON file:
> 
> ```
>     //// Loading sources
>     // Get contents through HTTP requests
>     function getContents(url, callback) {
>         var xhr = new XMLHttpRequest();
>         xhr.open("GET", url, true);
>         xhr.onload = callback;
>         xhr.send();
>     }
> 
>     // Read json file if json is available
>      $scope.openJSON = function(url) {
>         $scope.players = [];
>         $scope.buffer_empty_flag = [];
>         $scope.playerCount = 0;
>         $scope.lon = 90;
>         $scope.lat = 0;
>         $scope.contents = {};
>         getContents(url, function() {
>             $scope.contents = JSON.parse(this.responseText);
>             if ($scope.contents.ssresults && $scope.contents.ssresults != "") {
>                 getContents($scope.contents.baseUrl + $scope.contents.ssresults, function() {
>                     $scope.ssresults = JSON.parse(this.responseText);
>                 });
>             }
>             document.getElementById('Link').style = "display: none;";
>             document.getElementById('Render').style = "display: inline;";
>         });
>     };
> ```
> 
> Besides, your server needs to meet the requirement if you want to upload some data on it. One of the ways I used before is setting up a simple HTTP server that can deal with GET, POST, PUT methods. More details can be checked in some blogs on google, e.g. https://blog.anvileight.com/posts/simple-python-http-server.

Really appreciate your help. Thanks
